services:
    igdr_cache.manager.tags:
        class: Igdr\Bundle\CacheBundle\Manager\TagsManager
        arguments: [""]

    igdr_cache.manager.cache:
        class: Igdr\Bundle\CacheBundle\Manager\CacheManager
        arguments: ["", "@igdr_cache.manager.tags", ""]